# Aliases
alias reload="source ~/.zshrc"
alias bitch,="sudo"
alias please='eval "fc -lnr | head -n 1" | xargs sudo'
alias ports="lsof -i -P | grep -i listen"
fliptable() { echo "（╯°□°）╯ ┻━┻"; }


# Git aliases
alias gst="git status"
alias gs="git status"
alias gt="git tree"
alias gd="git diff"
alias gdc="git diff --cached"

# Fix hostname for mac
alias fixhost="scutil --set HostName martin-mbp && echo \"Now make sure martin-mpb exists in /etc/hosts. Press enter to edit it.\" && read && sudo vim /etc/hosts"
# No mouse acceleration
defaults write .GlobalPreferences com.apple.mouse.scaling -1

# Adds bin catalog in home directory
export PATH=~/bin:$PATH

# Add RVM to PATH for scripting
export PATH=$PATH:$HOME/.rvm/bin

# Add /usr/local/(s)bin first
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

export JAVA_TOOL_OPTIONS='-Djava.awt.headless=true'

# Unleash an awesome shell (either by oh-my-zsh, or by fallbacking on hacks.)
if [[ -a ~/.oh-my.zsh ]]
then
	source ~/.oh-my.zsh
else
	echo "Warning: Could not find ~/.oh-my.zsh, fallbacking on a crude PS1 config."
	# Enable colors
	export CLICOLOR=1
	# Use an awesome prompt
	export PS1="$(echo '%{\e[1;37m%}%c %{\e[0;31m%}%(!.☭.∴)%{\e[0m%} ')"
fi

# Fixes problem with perl whining about locale
export LC_CTYPE="en_US.UTF-8"
export LB_ALL="en_US.UTF-8"

if [[ -a ~/.localrc ]]
then
	source ~/.localrc
fi

# Maven specifics

function pom-release {
	if [[ $# == 0	 ]]; then
		echo "Usage: pom-release release-version next-version [extra-params]"
		return
	fi

	releaseversion=$1
	nextversion=$2
	arguments=$(shift; shift; echo $@)

	pom-set-version $1 $arguments
	git commit -am "Release version $1"
	git tag $1

	pom-set-version $2 $arguments
	git commit -am "Prepares for next version ($2)"
}

function pom-set-version {
	if [[ $# == 0 ]]; then
		echo "Usage: pom-set-version version [extra-params]"
		return
	fi
	version=$1
	arguments=$(shift; echo $@)

	echo "mvn versions:set -DnewVersion=$version -DprocessDependencies=false $arguments"
	mvn versions:set -DnewVersion=$version -DprocessDependencies=false $arguments
	echo "mvn versions:commit $arguments"
	mvn versions:commit $arguments

	if [[ -d ".git" ]]; then
		git diff
		git status
	fi
}

function pom-grep {
	if [[ $# == 0 ]]; then
		echo "Usage: pom-grep search-string"
	fi
	search_string="$@"
	grep -R -B 2 --include=pom.xml "$search_string" .

}

function pom-strip-snapshot {
	for pom in `find . -name pom.xml`; do 
		sed -e 's/-SNAPSHOT<\/\(.*\)version>/<\/\1version>/' -i '' $pom
	done
	# Linux version:
	# for pom in `find . -name pom.xml`; do sed -i 's/-SNAPSHOT<\/\(.*\)version>/<\/\1version>/' $pom; done

	if [[ -d ".git" ]]; then
		git diff
		git status
	fi
}
