# Aliases
alias reload="source ~/.zshrc"
alias bitch,="sudo"
alias please='eval "fc -lnr | head -n 1" | xargs sudo'
alias ports="lsof -i -P | grep -i listen"
fliptable() { echo "（╯°□°）╯ ┻━┻"; }


# Git aliases
alias gst="git status"
alias gs="git status"
alias gt="git tree"
alias gta="git alltree"
alias gd="git diff"
alias gdc="git diff --cached"

# Fix hostname for mac
alias fixhost="scutil --set HostName martin-mbp && echo \"Now make sure martin-mpb exists in /etc/hosts. Press enter to edit it.\" && read && sudo vim /etc/hosts"
# No mouse acceleration
defaults write .GlobalPreferences com.apple.mouse.scaling -1

# Always show hidden files in finder
defaults write com.apple.finder AppleShowAllFiles YES

# Adds bin catalog in home directory
export PATH=~/bin:$PATH

# Add RVM to PATH for scripting
export PATH=$PATH:$HOME/.rvm/bin

# Add /usr/local/(s)bin first
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

export JAVA_TOOL_OPTIONS='-Djava.awt.headless=true'

# Unleash an awesome shell (either by oh-my-zsh, or by fallbacking on hacks.)
if [[ -a ~/.oh-my.zsh ]]
then
	source ~/.oh-my.zsh
else
	echo "Warning: Could not find ~/.oh-my.zsh, fallbacking on a crude PS1 config."
	# Enable colors
	export CLICOLOR=1
	# Use an awesome prompt
	export PS1="$(echo '%{\e[1;37m%}%c %{\e[0;31m%}%(!.☭.∴)%{\e[0m%} ')"
fi

# Fixes problem with perl whining about locale
export LC_CTYPE="en_US.UTF-8"
export LB_ALL="en_US.UTF-8"

if [[ -a ~/.localrc ]]
then
	source ~/.localrc
fi

